name: Code Quality Checks

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  linting:
    name: Lint, Format, and Type Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit mypy black isort flake8 autoflake

      - name: Cache Pre-Commit Hooks
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            pre-commit-${{ runner.os }}

      - name: Run Pre-Commit Checks
        run: |
          pre-commit install --install-hooks
          pre-commit run --all-files --show-diff-on-failure --color=always

      - name: Verify Black Formatting
        run: black --check .

      - name: Verify Isort Formatting
        run: isort --profile black --check .