name: Run Unit and Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: docker compose version

      - name: Start services and run tests
        run: |
          if [[ "$(uname -m)" == "arm64" ]]; then
            echo "TF_IMAGE=emacski/tensorflow-serving:latest" >> $GITHUB_ENV
            echo "TF_PLATFORM=linux/arm64" >> $GITHUB_ENV
            echo "Using ARM64 TensorFlow image"
          else
            echo "TF_IMAGE=tensorflow/serving:latest" >> $GITHUB_ENV
            echo "TF_PLATFORM=linux/amd64" >> $GITHUB_ENV
            echo "Using AMD64 TensorFlow image"
          fi

          docker compose up -d

      - name: Stop and remove services
        run: docker compose down
