name: Run Unit and Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: docker compose version

      - name: Start services
        run: docker compose up -d

      - name: Wait for services to be ready
        run: |
          echo "Waiting for MongoDB and TensorFlow Serving to be ready..."

          # Wait for TensorFlow Serving
          timeout 140s bash -c 'until curl -s http://localhost:8501/v1/models/resnet; do echo "Waiting for TensorFlow Serving..."; sleep 2; done'
          echo "TensorFlow Serving is ready"

          # Wait for MongoDB
          timeout 60s bash -c 'until curl -s http://localhost:27017 > /dev/null; do echo "Waiting for MongoDB..."; sleep 2; done'
          echo "MongoDB is ready"

      - name: Run tests
        run: docker compose run --rm tests

      - name: Stop and remove services
        run: docker compose down
