name: Run Unit and Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: docker compose version

      - name: Start services
        run: docker compose up -d

      - name: Wait for services to be ready
        run: |
          echo "Waiting for MongoDB and TensorFlow Serving to be ready..."
          sleep 30

      - name: Run tests
        run: docker compose run --rm tests

      - name: Stop and remove services
        run: docker compose down
